import type { App } from '@/lib/types'

export const apps: App[] = [
  {
    id: '1',
    slug: 'gitcoin-grants-stack',
    name: 'Gitcoin Grants Stack',
    tagline: 'The easiest way to run a grants program',
    description: 'Grants Stack is a decentralized, modular protocol for running grants programs. It enables communities to fund their shared needs through quadratic funding, direct grants, and other mechanisms. Built on the Allo Protocol, it provides the infrastructure for democratic capital allocation.',
    logo: '/logos/gitcoin.svg',
    website: 'https://grants.gitcoin.co',
    category: 'platform',
    mechanisms: ['quadratic-funding', 'direct-grants'],
    blockchain: ['Ethereum', 'Arbitrum', 'Optimism', 'Polygon', 'Base'],
    launchDate: '2019-01-01',
    status: 'active',
    fundingVolume: '$60M+',
    socialLinks: {
      twitter: 'https://twitter.com/gitcoin',
      discord: 'https://discord.gg/gitcoin',
      github: 'https://github.com/gitcoinco',
    },
    tags: ['quadratic funding', 'grants', 'public goods', 'ethereum'],
    lastUpdated: '2024-12-01',
  },
  {
    id: '2',
    slug: 'optimism-retropgf',
    name: 'Optimism RetroPGF',
    tagline: 'Retroactive Public Goods Funding',
    description: 'Retroactive Public Goods Funding (RetroPGF) is Optimism\'s mechanism for rewarding public goods that have already demonstrated value. Instead of funding promises, it rewards proven impact, creating stronger incentives for building public goods.',
    logo: '/logos/optimism.svg',
    website: 'https://retrofunding.optimism.io',
    category: 'grant-program',
    mechanisms: ['retroactive-funding'],
    blockchain: ['Optimism'],
    launchDate: '2021-07-01',
    status: 'active',
    fundingVolume: '$100M+',
    socialLinks: {
      twitter: 'https://twitter.com/optimism',
      discord: 'https://discord.gg/optimism',
      github: 'https://github.com/ethereum-optimism',
    },
    tags: ['retroactive funding', 'optimism', 'public goods', 'impact'],
    lastUpdated: '2024-12-01',
  },
  {
    id: '3',
    slug: 'giveth',
    name: 'Giveth',
    tagline: 'Building the Future of Giving',
    description: 'Giveth is a community-driven platform for transparent, traceable donations to verified for-good projects. It combines direct donations with innovative mechanisms like GIVbacks that reward donors with tokens.',
    logo: '/logos/giveth.svg',
    website: 'https://giveth.io',
    category: 'platform',
    mechanisms: ['direct-grants', 'quadratic-funding'],
    blockchain: ['Ethereum', 'Gnosis', 'Polygon', 'Optimism'],
    launchDate: '2017-01-01',
    status: 'active',
    fundingVolume: '$10M+',
    socialLinks: {
      twitter: 'https://twitter.com/giveth',
      discord: 'https://discord.gg/giveth',
      github: 'https://github.com/Giveth',
    },
    tags: ['donations', 'givbacks', 'transparent', 'regenerative'],
    lastUpdated: '2024-11-15',
  },
  {
    id: '4',
    slug: 'clr-fund',
    name: 'clr.fund',
    tagline: 'Permissionless quadratic funding',
    description: 'clr.fund is a protocol for permissionless quadratic funding. Using MACI (Minimal Anti-Collusion Infrastructure), it provides bribery-resistant, private voting for democratic capital allocation.',
    logo: '/logos/clrfund.svg',
    website: 'https://clr.fund',
    category: 'primitive',
    mechanisms: ['quadratic-funding'],
    blockchain: ['Ethereum', 'Arbitrum'],
    launchDate: '2020-06-01',
    status: 'active',
    fundingVolume: '$2M+',
    socialLinks: {
      twitter: 'https://twitter.com/claboratory',
      github: 'https://github.com/clrfund',
    },
    tags: ['MACI', 'quadratic funding', 'bribery resistant', 'permissionless'],
    lastUpdated: '2024-10-01',
  },
  {
    id: '5',
    slug: 'protocol-guild',
    name: 'Protocol Guild',
    tagline: 'Funding Ethereum core contributors',
    description: 'Protocol Guild is a collective funding mechanism for Ethereum\'s core protocol contributors. It provides a simple way for the ecosystem to fund the people maintaining and developing Ethereum\'s base layer.',
    logo: '/logos/protocolguild.svg',
    website: 'https://protocol-guild.readthedocs.io',
    category: 'fund',
    mechanisms: ['streaming'],
    blockchain: ['Ethereum'],
    launchDate: '2022-05-01',
    status: 'active',
    fundingVolume: '$30M+',
    socialLinks: {
      twitter: 'https://twitter.com/ProtocolGuild',
      github: 'https://github.com/protocolguild',
    },
    tags: ['core protocol', 'ethereum', 'streaming', 'collective'],
    lastUpdated: '2024-12-01',
  },
  {
    id: '6',
    slug: 'arbitrum-dao-grants',
    name: 'Arbitrum DAO Grants',
    tagline: 'Funding the Arbitrum ecosystem',
    description: 'The Arbitrum DAO runs various grant programs to fund projects building on and contributing to the Arbitrum ecosystem. Programs include the Foundation grants, STIP, and community-led initiatives.',
    logo: '/logos/arbitrum.svg',
    website: 'https://arbitrum.foundation/grants',
    category: 'dao',
    mechanisms: ['direct-grants', 'milestone-based'],
    blockchain: ['Arbitrum'],
    launchDate: '2023-03-01',
    status: 'active',
    fundingVolume: '$200M+',
    socialLinks: {
      twitter: 'https://twitter.com/arbitrum',
      discord: 'https://discord.gg/arbitrum',
      github: 'https://github.com/OffchainLabs',
    },
    tags: ['arbitrum', 'grants', 'ecosystem', 'layer 2'],
    lastUpdated: '2024-12-01',
  },
  {
    id: '7',
    slug: 'octant',
    name: 'Octant',
    tagline: 'Public goods funding, powered by staking',
    description: 'Octant is a platform for participatory public goods funding. Users lock GLM tokens to earn ETH rewards, which can be donated to curated public goods projects or claimed personally.',
    logo: '/logos/octant.svg',
    website: 'https://octant.app',
    category: 'platform',
    mechanisms: ['quadratic-funding', 'direct-grants'],
    blockchain: ['Ethereum'],
    launchDate: '2023-08-01',
    status: 'active',
    fundingVolume: '$5M+',
    socialLinks: {
      twitter: 'https://twitter.com/OctantApp',
      discord: 'https://discord.gg/octant',
    },
    tags: ['staking', 'golem', 'epochs', 'participatory'],
    lastUpdated: '2024-11-15',
  },
  {
    id: '8',
    slug: 'drips',
    name: 'Drips',
    tagline: 'Streaming funding for open source',
    description: 'Drips enables continuous token streaming to fund open source dependencies. It creates sustainable funding flows from projects to their dependencies, acknowledging the supply chain of open source.',
    logo: '/logos/drips.svg',
    website: 'https://drips.network',
    category: 'primitive',
    mechanisms: ['streaming'],
    blockchain: ['Ethereum'],
    launchDate: '2023-01-01',
    status: 'active',
    fundingVolume: '$1M+',
    socialLinks: {
      twitter: 'https://twitter.com/draboratory',
      github: 'https://github.com/radicle-dev/drips',
    },
    tags: ['streaming', 'dependencies', 'open source', 'continuous'],
    lastUpdated: '2024-10-15',
  },
  {
    id: '9',
    slug: 'superfluid',
    name: 'Superfluid',
    tagline: 'Money streaming protocol',
    description: 'Superfluid is a smart contract framework for programmable money streams. It enables real-time finance applications including continuous salary payments, subscriptions, and streaming grants.',
    logo: '/logos/superfluid.svg',
    website: 'https://superfluid.finance',
    category: 'primitive',
    mechanisms: ['streaming'],
    blockchain: ['Ethereum', 'Polygon', 'Arbitrum', 'Optimism', 'Avalanche', 'BSC'],
    launchDate: '2021-01-01',
    status: 'active',
    fundingVolume: '$50M+',
    socialLinks: {
      twitter: 'https://twitter.com/Superfluid_HQ',
      discord: 'https://discord.gg/superfluid',
      github: 'https://github.com/superfluid-finance',
    },
    tags: ['streaming', 'real-time', 'programmable', 'DeFi'],
    lastUpdated: '2024-12-01',
  },
  {
    id: '10',
    slug: 'ethereum-foundation-grants',
    name: 'Ethereum Foundation Grants',
    tagline: 'Supporting Ethereum ecosystem growth',
    description: 'The Ethereum Foundation provides grants to teams and individuals working on projects that benefit the Ethereum ecosystem. Programs include the Ecosystem Support Program (ESP), academic grants, and targeted initiatives.',
    logo: '/logos/ef.svg',
    website: 'https://esp.ethereum.foundation',
    category: 'grant-program',
    mechanisms: ['direct-grants', 'milestone-based'],
    blockchain: ['Ethereum'],
    launchDate: '2014-01-01',
    status: 'active',
    fundingVolume: '$100M+',
    socialLinks: {
      twitter: 'https://twitter.com/EF_ESP',
      github: 'https://github.com/ethereum',
    },
    tags: ['ethereum foundation', 'ecosystem', 'research', 'development'],
    lastUpdated: '2024-12-01',
  },
  {
    id: '11',
    slug: 'allo-protocol',
    name: 'Allo Protocol',
    tagline: 'The infrastructure for capital allocation',
    description: 'Allo Protocol is an open-source protocol for capital allocation. It provides modular building blocks that developers can use to create any type of funding mechanism, from grants to milestone-based funding.',
    logo: '/logos/allo.svg',
    website: 'https://allo.gitcoin.co',
    category: 'primitive',
    mechanisms: ['quadratic-funding', 'direct-grants', 'milestone-based'],
    blockchain: ['Ethereum', 'Arbitrum', 'Optimism', 'Polygon', 'Base'],
    launchDate: '2023-06-01',
    status: 'active',
    socialLinks: {
      twitter: 'https://twitter.com/alloprotocol',
      github: 'https://github.com/allo-protocol',
    },
    tags: ['protocol', 'infrastructure', 'modular', 'capital allocation'],
    lastUpdated: '2024-12-01',
  },
  {
    id: '12',
    slug: 'nouns-dao',
    name: 'Nouns DAO',
    tagline: 'One Noun, Every Day, Forever',
    description: 'Nouns DAO is a generative avatar community that funds public goods and creative projects. With one NFT auctioned daily, the treasury funds proposals voted on by Noun holders.',
    logo: '/logos/nouns.svg',
    website: 'https://nouns.wtf',
    category: 'dao',
    mechanisms: ['direct-grants'],
    blockchain: ['Ethereum'],
    launchDate: '2021-08-01',
    status: 'active',
    fundingVolume: '$50M+',
    socialLinks: {
      twitter: 'https://twitter.com/nounsdao',
      discord: 'https://discord.gg/nouns',
    },
    tags: ['NFT', 'generative', 'treasury', 'proposals'],
    lastUpdated: '2024-11-01',
  },
]

export function getAppBySlug(slug: string): App | undefined {
  return apps.find((app) => app.slug === slug)
}

export function getAppsByCategory(category: string): App[] {
  return apps.filter((app) => app.category === category)
}

export function getAppsByMechanism(mechanism: string): App[] {
  return apps.filter((app) => app.mechanisms.includes(mechanism))
}

export function getFeaturedApps(count: number = 4): App[] {
  return apps.slice(0, count)
}
